version: '2'
services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile-nginx
    volumes:
      - /usr/share/nginx/html
      - /etc/letsencrypt
    external_links:
      - gubbns_gubbns_1:gubbns
    networks:
      - gubbns
    ports:
      - '80:80'
      - '443:443'
  certbot:
    build:
      context: .
      dockerfile: Dockerfile-certbot
    volumes_from:
      - nginx
    command: >
      certonly
      --non-interactive
      --agree-tos
      --webroot
      --expand
      --email jrc.collier@gmail.com
      --webroot-path /usr/share/nginx/html
      -d gubbns.com -d www.gubbns.com
  dockup:
    image: slakah/dockup-gs
    volumes_from:
      - certbot
    command: >
      gs://gubbns-backup/letsencrypt/
      /etc/letsencrypt
      --cron-time '54 4 * * *'
      --backup-name letsencrypt
      --gc-key '${GCLOUD_LETSENCRYPT_BACKUP_KEY}'

networks:
  gubbns:
    external:
      name: gubbns_default
