FROM slakah/docker-nginx

RUN apk add --update tini bash && rm -rf /var/cache/apk/*

COPY nginx/etc /etc
RUN echo "daemon off;" >> /etc/nginx/nginx.conf

COPY bin /
COPY nginx/docker-entrypoint.sh /

ENTRYPOINT ["tini", "--", "/wait-for-file.sh", "/etc/letsencrypt/.restored", "--"]
CMD ["nginx"]
